### ISSUE TITLE
[VS Code] Add Cellery Pane

### ISSUE THREAD

**Issue by nadundesilva** [wso2/cellery#939]
**Description:**
It might be useful for the user to provide an additional pane showing information about the Current runtime his/her environment is pointing to. (Similar to the pane provided by Docker VS Code extension)

**Approach:**
Add a pane using information collected by invoking the Cellery CLI. Details of how to do this (eg:- frequency of updates) is yet to be decided.

**Tasks:**
- [ ] Add support to provide CLI command output in a well-known format (eg:- JSON)
- [ ] Research and plan the approach
- [ ] Add VS Code Pane with the information
