### ISSUE TITLE
[VS Code] Cellery Diagram Support 

### ISSUE THREAD

**Issue by nadundesilva** [wso2/cellery#940]
**Description:**
As of now, to view the Cellery diagram, the user needs to build an image out of it and run `cellery view` command. While this serves the purpose of viewing a quick documentation of an Image, providing this diagram as part of the VS Code extension would be helpful for the user in the development iterations.

**Approach:**
The Cell files needs to be built and the `artifacts/cellery/metadata.json` file needs to be read to extract the relevant information about the Cell file. This data can be easily converted to a diagram using the React Component used in CLI and Cellery Hub.

**Tasks:**
- [ ] Add support to run build without saving the image to the local repository (only create the image in target directory)
- [ ] Add support to start an instance from a Cellery Image file which is not in the local repository.
- [ ] Add Cellery Web View from the VS Code extension to show the diagram (a button should be provided in the view to trigger the build as building always can affect performance)
