### ISSUE TITLE
[VS Code] Add support to build, test and deploy Cell file from VS Code

### ISSUE THREAD

**Issue by nadundesilva** [wso2/cellery#942]
**Description:**
Currently the user can build. run and test Cell files by going through the normal CLI flows. However, it would be useful to provide the ability to quickly build, run and test Cell files directly from VS Code itself for improving the development cycles.

**Approach:**
VS Code commands needs to be added to build, run and test the currently open Cell file from VS Code itself.

**Tasks:**
- [x] Add VS Code Build, Run and Test commands
- [x] Add support to remember the previous inputs given by the user and provide them as Quick Pick
- [x] Update logs command to support only showing component logs
- [ ] Check the possibility of tailing logs (since logs are shown right after the instance is started)
- [ ] Add component name prefix to the logs

**Comment by madushajg** [comment]
> Check the possibility of tailing logs (since logs are shown right after the instance is started)

This is implemented for k8s client version 1.14 onwards. When there are more than five logs streams running for a cell instance, it is impossible to follow logs for that cell instance since k8s only support up to five log streams. From K8s 1.14, they introduced a flag to configure the number of log streams and hence the tailing cell logs functionality only supported for k8s 1.14 and later versions.

> Add component name prefix to the logs

This feature is not implemented since there is no clean way to derive components separately since we are using label selector with `--all-containers` flag to show cell instance logs. However, [k8s 1.17](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.17.md#cli-improvements) introduced `--prefix` flag to prepend each log line with information about it's source (pod name and container name) and we can use this to add component name prefix to the logs in the future.
