### ISSUE TITLE
[VS Code] Provide Basic Language Support for Cellery

### ISSUE THREAD

**Issue by nadundesilva** [wso2/cellery#943]
**Description:**
As of now, Cellery relies solely on Ballerina Tooling support. While this provides a lot of features, with Cellery extensions we will be able to provide additional completions.

**Approach:**
Ballerina Language Server extension points will be used for injecting additional snippets and completions through the Ballerina Extension itself.

**Tasks:**
- [x] Add Ballerina as an Extension Dependency
- [x] Create basic structure for adding plugins to the Ballerina Lang Server
- [x] Add basic set of snippets for improving Cell developer experience
- [x] Add reference key completions
- [x] Add image completions
